CREATE TABLE `ai_ab_experiments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`experimentId` varchar(50) NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`feature` varchar(100) NOT NULL,
	`controlConfig` json NOT NULL,
	`treatmentConfig` json NOT NULL,
	`trafficAllocation` decimal(3,2) DEFAULT '0.50',
	`primaryMetric` varchar(100) NOT NULL,
	`secondaryMetrics` json,
	`controlSampleSize` int DEFAULT 0,
	`treatmentSampleSize` int DEFAULT 0,
	`controlMetricValue` decimal(10,4),
	`treatmentMetricValue` decimal(10,4),
	`statisticalSignificance` decimal(5,4),
	`status` enum('draft','running','paused','completed','cancelled') NOT NULL DEFAULT 'draft',
	`winner` enum('control','treatment','inconclusive'),
	`startedAt` timestamp,
	`endedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`createdBy` int NOT NULL,
	CONSTRAINT `ai_ab_experiments_id` PRIMARY KEY(`id`),
	CONSTRAINT `ai_ab_experiments_experimentId_unique` UNIQUE(`experimentId`)
);
--> statement-breakpoint
CREATE TABLE `ai_feedback_advanced` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`messageId` int,
	`insightId` int,
	`actionId` int,
	`predictionId` int,
	`rating` int NOT NULL,
	`feedbackType` enum('like','dislike','neutral') NOT NULL,
	`comment` text NOT NULL,
	`improvementAreas` json,
	`interactionType` enum('chat','insight','alert','action','prediction') NOT NULL,
	`responseTimeMs` int,
	`sessionDuration` int,
	`language` varchar(10) DEFAULT 'pt-BR',
	`experimentId` varchar(50),
	`variant` varchar(20),
	`contextSnapshot` json,
	`userSegment` varchar(50),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`processedAt` timestamp,
	`processedForRetrain` boolean DEFAULT false,
	CONSTRAINT `ai_feedback_advanced_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ai_performance_reports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`reportType` enum('monthly','quarterly','annual') NOT NULL,
	`periodStart` date NOT NULL,
	`periodEnd` date NOT NULL,
	`totalInteractions` int NOT NULL,
	`uniqueUsers` int NOT NULL,
	`avgSessionDuration` int,
	`totalFeedbacks` int NOT NULL,
	`feedbackRate` decimal(5,4),
	`avgRating` decimal(3,2),
	`satisfactionRate` decimal(5,4),
	`suggestionAcceptanceRate` decimal(5,4),
	`alertAccuracyRate` decimal(5,4),
	`predictionAccuracyRate` decimal(5,4),
	`interactionsByLanguage` json,
	`abTestResults` json,
	`insightsGenerated` int NOT NULL,
	`insightsResolved` int NOT NULL,
	`insightsDismissed` int NOT NULL,
	`actionsSuggested` int NOT NULL,
	`actionsApproved` int NOT NULL,
	`actionsExecuted` int NOT NULL,
	`predictionsGenerated` int NOT NULL,
	`predictionsValidated` int NOT NULL,
	`trend` enum('improving','stable','declining') DEFAULT 'stable',
	`trendDetails` json,
	`recommendations` json,
	`generatedAt` timestamp NOT NULL DEFAULT (now()),
	`generatedBy` int,
	CONSTRAINT `ai_performance_reports_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ai_retrain_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`modelType` varchar(50) NOT NULL,
	`triggerType` enum('scheduled','feedback_threshold','manual') NOT NULL,
	`previousAccuracy` decimal(5,4),
	`previousFeedbackScore` decimal(5,4),
	`newAccuracy` decimal(5,4),
	`newFeedbackScore` decimal(5,4),
	`feedbackCount` int NOT NULL,
	`dataPointsUsed` int NOT NULL,
	`trainingDurationMs` int,
	`thresholdsAdjusted` json,
	`parametersChanged` json,
	`status` enum('started','completed','failed','rolled_back') NOT NULL DEFAULT 'started',
	`errorMessage` text,
	`dataRetentionDays` int DEFAULT 365,
	`anonymizationApplied` boolean DEFAULT true,
	`startedAt` timestamp NOT NULL DEFAULT (now()),
	`completedAt` timestamp,
	`createdBy` int,
	CONSTRAINT `ai_retrain_logs_id` PRIMARY KEY(`id`)
);
