CREATE TABLE `backup_records` (
	`id` int AUTO_INCREMENT NOT NULL,
	`type` enum('full','incremental','differential') NOT NULL,
	`status` enum('running','completed','failed') NOT NULL DEFAULT 'running',
	`startedAt` timestamp NOT NULL DEFAULT (now()),
	`completedAt` timestamp,
	`sizeBytes` int,
	`location` varchar(500),
	`checksum` varchar(64),
	`retentionDays` int DEFAULT 30,
	`expiresAt` timestamp,
	`errorMessage` text,
	`restorable` boolean DEFAULT true,
	`lastRestoreTest` timestamp,
	`createdBy` int,
	CONSTRAINT `backup_records_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `checklist_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`checklistId` int NOT NULL,
	`category` enum('limpeza','epi','calibracao','seguranca','qualidade','documentacao') NOT NULL,
	`description` varchar(500) NOT NULL,
	`required` boolean DEFAULT true,
	`checked` boolean DEFAULT false,
	`checkedAt` timestamp,
	`checkedBy` int,
	`photoUrl` varchar(500),
	`observations` text,
	`nonConformity` boolean DEFAULT false,
	CONSTRAINT `checklist_items_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `checklist_templates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`shift` enum('manha','tarde','noite','todos') DEFAULT 'todos',
	`active` boolean DEFAULT true,
	`items` json NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`createdBy` int,
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `checklist_templates_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `compliance_documents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`type` enum('alvara','licenca_ambiental','licenca_sanitaria','certificado','iso','organico','outro') NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`documentNumber` varchar(100),
	`issuingBody` varchar(255),
	`issueDate` date,
	`expirationDate` date,
	`renewalAlertDays` int DEFAULT 30,
	`status` enum('vigente','vencido','em_renovacao','cancelado') NOT NULL DEFAULT 'vigente',
	`fileUrl` varchar(500),
	`observations` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`createdBy` int,
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `compliance_documents_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `customers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`externalCode` varchar(50),
	`name` varchar(255) NOT NULL,
	`tradeName` varchar(255),
	`cpfCnpj` varchar(20) NOT NULL,
	`type` enum('varejo','atacado','industria','distribuidor','exportacao') NOT NULL,
	`phone` varchar(20),
	`email` varchar(320),
	`address` text,
	`city` varchar(100),
	`state` varchar(2),
	`contactName` varchar(255),
	`paymentTerms` varchar(100),
	`creditLimit` decimal(14,2),
	`status` enum('ativo','inativo','bloqueado') NOT NULL DEFAULT 'ativo',
	`firstPurchaseDate` date,
	`lastPurchaseDate` date,
	`totalPurchases` decimal(14,2) DEFAULT '0',
	`averageTicket` decimal(14,2) DEFAULT '0',
	`observations` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`createdBy` int,
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `customers_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `equipments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`code` varchar(20) NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`type` enum('secadora','ralador','peneira','embaladora','balanca','esteira','lavadora','outro') NOT NULL,
	`manufacturer` varchar(255),
	`model` varchar(100),
	`serialNumber` varchar(100),
	`location` varchar(100),
	`acquisitionDate` date,
	`acquisitionCost` decimal(14,2),
	`warrantyExpiration` date,
	`status` enum('operacional','manutencao','parado','desativado') NOT NULL DEFAULT 'operacional',
	`lastMaintenanceDate` date,
	`nextMaintenanceDate` date,
	`maintenanceIntervalDays` int DEFAULT 90,
	`hourMeter` decimal(10,2) DEFAULT '0',
	`specifications` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`createdBy` int,
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `equipments_id` PRIMARY KEY(`id`),
	CONSTRAINT `equipments_code_unique` UNIQUE(`code`)
);
--> statement-breakpoint
CREATE TABLE `magic_moments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`type` enum('fechamento_turno','pagamento_produtor','estoque_critico','meta_batida','novo_recorde','economia_identificada','problema_evitado','cliente_especial','aniversario_parceria','fim_semana_tranquilo','novo_funcionario','auditoria_simplificada') NOT NULL,
	`title` varchar(255) NOT NULL,
	`message` text NOT NULL,
	`data` json,
	`targetUserId` int,
	`targetRole` varchar(50),
	`seen` boolean DEFAULT false,
	`seenAt` timestamp,
	`notificationSent` boolean DEFAULT false,
	`notificationSentAt` timestamp,
	`notificationChannel` enum('app','email','whatsapp','push'),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `magic_moments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `maintenance_records` (
	`id` int AUTO_INCREMENT NOT NULL,
	`equipmentId` int NOT NULL,
	`type` enum('preventiva','corretiva','preditiva','emergencial') NOT NULL,
	`description` text NOT NULL,
	`cause` text,
	`solution` text,
	`startedAt` timestamp NOT NULL,
	`completedAt` timestamp,
	`downtimeMinutes` int,
	`cost` decimal(14,2),
	`laborCost` decimal(14,2),
	`partsCost` decimal(14,2),
	`technicianName` varchar(255),
	`externalService` boolean DEFAULT false,
	`status` enum('agendada','em_andamento','concluida','cancelada') NOT NULL DEFAULT 'agendada',
	`priority` enum('baixa','media','alta','critica') NOT NULL DEFAULT 'media',
	`photoUrl` varchar(500),
	`observations` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`createdBy` int,
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `maintenance_records_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `production_costs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`productionOrderId` int,
	`batchNumber` varchar(50),
	`skuId` int NOT NULL,
	`productionDate` date NOT NULL,
	`quantityProduced` decimal(10,2) NOT NULL,
	`rawMaterialCost` decimal(14,2) DEFAULT '0',
	`packagingCost` decimal(14,2) DEFAULT '0',
	`laborCost` decimal(14,2) DEFAULT '0',
	`energyCost` decimal(14,2) DEFAULT '0',
	`overheadCost` decimal(14,2) DEFAULT '0',
	`maintenanceCost` decimal(14,2) DEFAULT '0',
	`depreciationCost` decimal(14,2) DEFAULT '0',
	`totalDirectCost` decimal(14,2) DEFAULT '0',
	`totalIndirectCost` decimal(14,2) DEFAULT '0',
	`totalCost` decimal(14,2) DEFAULT '0',
	`unitCost` decimal(14,4) DEFAULT '0',
	`standardUnitCost` decimal(14,4),
	`costVariance` decimal(14,4),
	`costVariancePercent` decimal(5,2),
	`observations` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`createdBy` int,
	CONSTRAINT `production_costs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `production_goals` (
	`id` int AUTO_INCREMENT NOT NULL,
	`type` enum('diaria','semanal','mensal','turno') NOT NULL,
	`shift` enum('manha','tarde','noite','todos'),
	`skuId` int,
	`targetQuantity` decimal(10,2) NOT NULL,
	`targetYield` decimal(5,2),
	`maxLossPercent` decimal(5,2),
	`startDate` date NOT NULL,
	`endDate` date,
	`status` enum('ativa','inativa','concluida') NOT NULL DEFAULT 'ativa',
	`achievedQuantity` decimal(10,2) DEFAULT '0',
	`achievedPercent` decimal(5,2) DEFAULT '0',
	`achievedAt` timestamp,
	`observations` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`createdBy` int,
	CONSTRAINT `production_goals_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `production_orders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`orderNumber` varchar(20) NOT NULL,
	`skuId` int NOT NULL,
	`variation` enum('flocos','medio','fino') NOT NULL,
	`plannedQuantity` decimal(10,2) NOT NULL,
	`producedQuantity` decimal(10,2) DEFAULT '0',
	`plannedStartDate` date NOT NULL,
	`plannedEndDate` date,
	`actualStartDate` timestamp,
	`actualEndDate` timestamp,
	`priority` enum('baixa','normal','alta','urgente') NOT NULL DEFAULT 'normal',
	`status` enum('aguardando','em_producao','qualidade','concluida','cancelada') NOT NULL DEFAULT 'aguardando',
	`batchNumber` varchar(50),
	`estimatedYield` decimal(5,2),
	`actualYield` decimal(5,2),
	`observations` text,
	`kanbanColumn` enum('backlog','aguardando','em_producao','qualidade','concluida') DEFAULT 'backlog',
	`kanbanPosition` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`createdBy` int,
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `production_orders_id` PRIMARY KEY(`id`),
	CONSTRAINT `production_orders_orderNumber_unique` UNIQUE(`orderNumber`)
);
--> statement-breakpoint
CREATE TABLE `production_reprocesses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`originalBatchNumber` varchar(50) NOT NULL,
	`newBatchNumber` varchar(50),
	`productionOrderId` int,
	`skuId` int NOT NULL,
	`quantity` decimal(10,2) NOT NULL,
	`reason` enum('umidade_alta','granulometria','cor','contaminacao_leve','embalagem_danificada','outro') NOT NULL,
	`reasonDetail` text,
	`reprocessDate` date NOT NULL,
	`reprocessedQuantity` decimal(10,2),
	`lossQuantity` decimal(10,2),
	`additionalCost` decimal(14,2),
	`status` enum('aguardando','em_reprocesso','concluido','descartado') NOT NULL DEFAULT 'aguardando',
	`qualityApproved` boolean,
	`observations` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`createdBy` int,
	CONSTRAINT `production_reprocesses_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `production_stages` (
	`id` int AUTO_INCREMENT NOT NULL,
	`productionOrderId` int NOT NULL,
	`stage` enum('recepcao','selecao','lavagem','ralagem','secagem','peneiramento','embalagem') NOT NULL,
	`sequence` int NOT NULL,
	`equipmentId` int,
	`responsibleId` int,
	`responsibleName` varchar(255),
	`plannedDurationMinutes` int,
	`actualDurationMinutes` int,
	`inputQuantity` decimal(10,2),
	`outputQuantity` decimal(10,2),
	`lossQuantity` decimal(10,2) DEFAULT '0',
	`lossReason` text,
	`temperature` decimal(5,2),
	`humidity` decimal(5,2),
	`status` enum('pendente','em_andamento','concluida','pulada') NOT NULL DEFAULT 'pendente',
	`startedAt` timestamp,
	`completedAt` timestamp,
	`observations` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `production_stages_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `production_stops` (
	`id` int AUTO_INCREMENT NOT NULL,
	`productionOrderId` int,
	`equipmentId` int,
	`shift` enum('manha','tarde','noite') NOT NULL,
	`stopDate` date NOT NULL,
	`reason` enum('setup','manutencao_preventiva','manutencao_corretiva','falta_material','falta_operador','quebra','limpeza','qualidade','energia','outro') NOT NULL,
	`reasonDetail` text,
	`startedAt` timestamp NOT NULL,
	`endedAt` timestamp,
	`durationMinutes` int,
	`plannedStop` boolean DEFAULT false,
	`productionLostKg` decimal(10,2),
	`costImpact` decimal(14,2),
	`actionTaken` text,
	`preventable` boolean,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`createdBy` int,
	CONSTRAINT `production_stops_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `sales_order_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`salesOrderId` int NOT NULL,
	`skuId` int NOT NULL,
	`variation` enum('flocos','medio','fino'),
	`quantity` decimal(10,2) NOT NULL,
	`unitPrice` decimal(14,2) NOT NULL,
	`discountPercent` decimal(5,2) DEFAULT '0',
	`totalPrice` decimal(14,2) NOT NULL,
	`batchNumber` varchar(50),
	CONSTRAINT `sales_order_items_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `sales_orders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`orderNumber` varchar(20) NOT NULL,
	`customerId` int NOT NULL,
	`orderDate` timestamp NOT NULL DEFAULT (now()),
	`deliveryDate` date,
	`status` enum('orcamento','confirmado','em_separacao','faturado','enviado','entregue','cancelado') NOT NULL DEFAULT 'orcamento',
	`totalValue` decimal(14,2) NOT NULL,
	`discountPercent` decimal(5,2) DEFAULT '0',
	`discountValue` decimal(14,2) DEFAULT '0',
	`netValue` decimal(14,2) NOT NULL,
	`paymentMethod` varchar(100),
	`paymentTerms` varchar(100),
	`shippingMethod` varchar(100),
	`shippingCost` decimal(14,2) DEFAULT '0',
	`observations` text,
	`internalNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`createdBy` int,
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `sales_orders_id` PRIMARY KEY(`id`),
	CONSTRAINT `sales_orders_orderNumber_unique` UNIQUE(`orderNumber`)
);
--> statement-breakpoint
CREATE TABLE `security_policies` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(100) NOT NULL,
	`description` text,
	`minPasswordLength` int DEFAULT 8,
	`requireUppercase` boolean DEFAULT true,
	`requireLowercase` boolean DEFAULT true,
	`requireNumbers` boolean DEFAULT true,
	`requireSpecialChars` boolean DEFAULT false,
	`passwordExpirationDays` int DEFAULT 90,
	`passwordHistoryCount` int DEFAULT 5,
	`maxLoginAttempts` int DEFAULT 5,
	`lockoutDurationMinutes` int DEFAULT 30,
	`sessionTimeoutMinutes` int DEFAULT 480,
	`maxConcurrentSessions` int DEFAULT 3,
	`require2FA` boolean DEFAULT false,
	`require2FAForRoles` json,
	`active` boolean DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `security_policies_id` PRIMARY KEY(`id`),
	CONSTRAINT `security_policies_name_unique` UNIQUE(`name`)
);
--> statement-breakpoint
CREATE TABLE `sensor_readings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`equipmentId` int,
	`sensorType` enum('temperatura','umidade','peso','pressao','vibracao','energia') NOT NULL,
	`sensorCode` varchar(50),
	`value` decimal(10,4) NOT NULL,
	`unit` varchar(20) NOT NULL,
	`minLimit` decimal(10,4),
	`maxLimit` decimal(10,4),
	`outOfSpec` boolean DEFAULT false,
	`productionOrderId` int,
	`batchNumber` varchar(50),
	`readAt` timestamp NOT NULL DEFAULT (now()),
	`source` enum('manual','automatico','iot') DEFAULT 'manual',
	CONSTRAINT `sensor_readings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `shift_checklists` (
	`id` int AUTO_INCREMENT NOT NULL,
	`checklistDate` date NOT NULL,
	`shift` enum('manha','tarde','noite') NOT NULL,
	`responsibleId` int,
	`responsibleName` varchar(255) NOT NULL,
	`status` enum('pendente','em_andamento','concluido','incompleto') NOT NULL DEFAULT 'pendente',
	`startedAt` timestamp,
	`completedAt` timestamp,
	`totalItems` int DEFAULT 0,
	`completedItems` int DEFAULT 0,
	`blocksProduction` boolean DEFAULT true,
	`observations` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `shift_checklists_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `user_two_factor` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`method` enum('totp','sms','email') NOT NULL DEFAULT 'totp',
	`secret` varchar(255),
	`phone` varchar(20),
	`backupCodes` json,
	`enabled` boolean DEFAULT false,
	`verifiedAt` timestamp,
	`lastUsedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `user_two_factor_id` PRIMARY KEY(`id`),
	CONSTRAINT `user_two_factor_userId_unique` UNIQUE(`userId`)
);
