CREATE TABLE `budget_actuals` (
	`id` int AUTO_INCREMENT NOT NULL,
	`budgetLineId` int NOT NULL,
	`month` int NOT NULL,
	`year` int NOT NULL,
	`actualValue` decimal(14,2) NOT NULL,
	`budgetedValue` decimal(14,2) NOT NULL,
	`varianceValue` decimal(14,2) NOT NULL,
	`variancePercent` decimal(8,2) NOT NULL,
	`status` enum('verde','amarelo','vermelho') NOT NULL,
	`sourceType` varchar(100),
	`sourceId` int,
	`observations` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `budget_actuals_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `budget_ai_insights` (
	`id` int AUTO_INCREMENT NOT NULL,
	`budgetId` int NOT NULL,
	`budgetLineId` int,
	`type` enum('alerta','previsao','sugestao','anomalia','otimizacao') NOT NULL,
	`severity` enum('info','warning','critical') NOT NULL DEFAULT 'info',
	`title` varchar(255) NOT NULL,
	`description` text NOT NULL,
	`actionSuggested` text,
	`potentialSavings` decimal(14,2),
	`confidence` decimal(5,2),
	`dataPoints` json,
	`status` enum('novo','visualizado','em_analise','resolvido','ignorado') NOT NULL DEFAULT 'novo',
	`resolvedBy` int,
	`resolvedAt` timestamp,
	`resolution` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`expiresAt` timestamp,
	CONSTRAINT `budget_ai_insights_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `budget_approvals` (
	`id` int AUTO_INCREMENT NOT NULL,
	`budgetId` int NOT NULL,
	`step` int NOT NULL,
	`role` enum('gerente','diretor','ceo') NOT NULL,
	`status` enum('pendente','aprovado','rejeitado','delegado') NOT NULL DEFAULT 'pendente',
	`assignedTo` int NOT NULL,
	`delegatedTo` int,
	`delegatedReason` text,
	`approvedBy` int,
	`approvedAt` timestamp,
	`comments` text,
	`minValue` decimal(18,2),
	`maxValue` decimal(18,2),
	`dueDate` timestamp,
	`reminderSent` boolean DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `budget_approvals_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `budget_forecasts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`budgetId` int NOT NULL,
	`budgetLineId` int,
	`forecastMonth` int NOT NULL,
	`forecastYear` int NOT NULL,
	`targetMonth` int NOT NULL,
	`targetYear` int NOT NULL,
	`originalBudget` decimal(14,2) NOT NULL,
	`previousForecast` decimal(14,2),
	`currentForecast` decimal(14,2) NOT NULL,
	`actualToDate` decimal(14,2) DEFAULT '0',
	`varianceFromBudget` decimal(14,2),
	`varianceFromPrevious` decimal(14,2),
	`confidenceLevel` enum('alta','media','baixa') DEFAULT 'media',
	`aiSuggestion` text,
	`aiConfidence` decimal(5,2),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`createdBy` int,
	CONSTRAINT `budget_forecasts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `budget_indicators` (
	`id` int AUTO_INCREMENT NOT NULL,
	`budgetId` int NOT NULL,
	`month` int NOT NULL,
	`year` int NOT NULL,
	`burnRate` decimal(8,2),
	`runRate` decimal(18,2),
	`varianceAccumulated` decimal(18,2),
	`adherenceIndex` decimal(5,2),
	`linesOnBudget` int DEFAULT 0,
	`linesOverBudget` int DEFAULT 0,
	`linesUnderBudget` int DEFAULT 0,
	`projectedYearEnd` decimal(18,2),
	`projectedVariance` decimal(18,2),
	`riskLevel` enum('baixo','medio','alto','critico') DEFAULT 'baixo',
	`aiAnalysis` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `budget_indicators_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `budget_lines` (
	`id` int AUTO_INCREMENT NOT NULL,
	`budgetId` int NOT NULL,
	`costCenter` enum('producao','comercial','administrativo','rh','manutencao','qualidade','logistica','ti') NOT NULL,
	`category` enum('receita_vendas','receita_servicos','receita_outras','custo_materia_prima','custo_mao_obra_direta','custo_energia','custo_embalagem','despesa_pessoal','despesa_aluguel','despesa_utilidades','despesa_marketing','despesa_manutencao','despesa_transporte','despesa_administrativa','despesa_outras','investimento_equipamento','investimento_infraestrutura','investimento_tecnologia','investimento_outros') NOT NULL,
	`isCapex` boolean DEFAULT false,
	`description` varchar(500),
	`jan` decimal(14,2) DEFAULT '0',
	`fev` decimal(14,2) DEFAULT '0',
	`mar` decimal(14,2) DEFAULT '0',
	`abr` decimal(14,2) DEFAULT '0',
	`mai` decimal(14,2) DEFAULT '0',
	`jun` decimal(14,2) DEFAULT '0',
	`jul` decimal(14,2) DEFAULT '0',
	`ago` decimal(14,2) DEFAULT '0',
	`set` decimal(14,2) DEFAULT '0',
	`out` decimal(14,2) DEFAULT '0',
	`nov` decimal(14,2) DEFAULT '0',
	`dez` decimal(14,2) DEFAULT '0',
	`totalYear` decimal(18,2) DEFAULT '0',
	`justification` text,
	`priority` enum('essencial','importante','desejavel') DEFAULT 'importante',
	`roiPercent` decimal(8,2),
	`paybackMonths` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`createdBy` int,
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`updatedBy` int,
	CONSTRAINT `budget_lines_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `budget_revisions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`budgetId` int NOT NULL,
	`budgetLineId` int,
	`revisionNumber` int NOT NULL,
	`revisionType` enum('criacao','ajuste','realocacao','corte','suplementacao') NOT NULL,
	`previousValue` decimal(14,2),
	`newValue` decimal(14,2),
	`changePercent` decimal(8,2),
	`reason` text NOT NULL,
	`approvedBy` int,
	`approvedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`createdBy` int,
	CONSTRAINT `budget_revisions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `budget_scenarios` (
	`id` int AUTO_INCREMENT NOT NULL,
	`budgetId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`type` enum('conservador','moderado','otimista') NOT NULL,
	`assumptions` json,
	`revenueAdjustment` decimal(8,2) DEFAULT '0',
	`expenseAdjustment` decimal(8,2) DEFAULT '0',
	`inflationRate` decimal(5,2) DEFAULT '0',
	`growthRate` decimal(5,2) DEFAULT '0',
	`totalRevenue` decimal(18,2) DEFAULT '0',
	`totalExpenses` decimal(18,2) DEFAULT '0',
	`netResult` decimal(18,2) DEFAULT '0',
	`isActive` boolean DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`createdBy` int,
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `budget_scenarios_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `budgets` (
	`id` int AUTO_INCREMENT NOT NULL,
	`year` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`type` enum('anual','mensal','trimestral') NOT NULL DEFAULT 'anual',
	`scenario` enum('conservador','moderado','otimista','base_zero') NOT NULL DEFAULT 'moderado',
	`status` enum('rascunho','em_aprovacao','aprovado','revisao','encerrado') NOT NULL DEFAULT 'rascunho',
	`baseYear` int,
	`adjustmentPercent` decimal(5,2) DEFAULT '0',
	`totalRevenue` decimal(18,2) DEFAULT '0',
	`totalExpenses` decimal(18,2) DEFAULT '0',
	`totalCapex` decimal(18,2) DEFAULT '0',
	`approvedBy` int,
	`approvedAt` timestamp,
	`observations` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`createdBy` int,
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`updatedBy` int,
	CONSTRAINT `budgets_id` PRIMARY KEY(`id`)
);
