CREATE TABLE `bank_accounts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`bankName` varchar(100) NOT NULL,
	`bankCode` varchar(10),
	`agency` varchar(20),
	`accountNumber` varchar(30) NOT NULL,
	`accountType` enum('corrente','poupanca','investimento','caixa') NOT NULL,
	`accountHolder` varchar(200),
	`cnpjCpf` varchar(20),
	`pixKey` varchar(100),
	`initialBalance` decimal(15,2) NOT NULL DEFAULT '0',
	`currentBalance` decimal(15,2) NOT NULL DEFAULT '0',
	`isActive` boolean NOT NULL DEFAULT true,
	`isDefault` boolean NOT NULL DEFAULT false,
	`chartOfAccountId` int,
	`color` varchar(7),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`createdBy` int,
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`updatedBy` int,
	CONSTRAINT `bank_accounts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `bank_transactions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`bankAccountId` int NOT NULL,
	`type` enum('credito','debito','transferencia') NOT NULL,
	`category` enum('receita_vendas','receita_outros','pagamento_produtor','pagamento_fornecedor','pagamento_funcionario','pagamento_imposto','pagamento_servico','tarifa_bancaria','transferencia_entre_contas','rendimento','emprestimo','investimento','outros') NOT NULL,
	`description` varchar(300) NOT NULL,
	`amount` decimal(15,2) NOT NULL,
	`balanceAfter` decimal(15,2),
	`transactionDate` date NOT NULL,
	`competenceDate` date,
	`documentNumber` varchar(50),
	`chartOfAccountId` int,
	`relatedEntityType` varchar(50),
	`relatedEntityId` int,
	`transferToAccountId` int,
	`reconciled` boolean NOT NULL DEFAULT false,
	`reconciledAt` timestamp,
	`reconciledBy` int,
	`attachmentUrl` varchar(500),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`createdBy` int,
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`updatedBy` int,
	CONSTRAINT `bank_transactions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `chart_of_accounts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`code` varchar(20) NOT NULL,
	`name` varchar(200) NOT NULL,
	`nature` enum('ativo','passivo','receita','despesa','patrimonio_liquido') NOT NULL,
	`type` enum('sintetica','analitica') NOT NULL,
	`level` int NOT NULL,
	`parentId` int,
	`description` text,
	`isActive` boolean NOT NULL DEFAULT true,
	`acceptsEntries` boolean NOT NULL DEFAULT false,
	`displayOrder` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`createdBy` int,
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`updatedBy` int,
	CONSTRAINT `chart_of_accounts_id` PRIMARY KEY(`id`),
	CONSTRAINT `chart_of_accounts_code_unique` UNIQUE(`code`)
);
